### PR TITLE
Own 10C47

### PR DESCRIPTION
**Pull request by Mercury13**
As this 10C47 is drawn with ink only, who knows its intended shape…

### CODE REVIEW

**Comment by Mercury13** [comment]
My license for this is simple.
You do what the funk you want.

**Comment by Mercury13** [comment]
Should close bug #2

**Comment by Mercury13** [comment]
Hope everything’s OK with stroke width…

**Comment by Mercury13** [comment]
Now really OK.

**Comment by simoncozens** [comment]
I'm really sorry, for some reason I didn't notice this! Thanks very much for the contribution.

**Pull request merged**
